### ISSUE TITLE
saga spring demo 启动报错

### ISSUE THREAD

**Issue by minlywang** [apache/incubator-servicecomb-saga#293]
.   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v1.5.14.RELEASE)

2018-09-11 19:30:50.235  INFO 38844 --- [           main] o.a.s.saga.demo.pack.car.Application     : Starting Application on fe-wangmingl-1 with PID 38844 (C:\Users\wangminglei01\git\incubator-servicecomb-saga\saga-demo\saga-spring-demo\car\target\classes started by wangminglei01 in C:\Users\wangminglei01\git\incubator-servicecomb-saga\saga-demo\saga-spring-demo\car)
2018-09-11 19:30:50.238  INFO 38844 --- [           main] o.a.s.saga.demo.pack.car.Application     : No active profile set, falling back to default profiles: default
2018-09-11 19:30:50.306  INFO 38844 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7f552bd3: startup date [Tue Sep 11 19:30:50 CST 2018]; root of context hierarchy
2018-09-11 19:30:51.468  INFO 38844 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.apache.servicecomb.saga.omega.transaction.spring.TransactionAspectConfig' of type [org.apache.servicecomb.saga.omega.transaction.spring.TransactionAspectConfig$$EnhancerBySpringCGLIB$$c631e80] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-09-11 19:30:52.415  INFO 38844 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.apache.servicecomb.saga.omega.spring.OmegaSpringConfig' of type [org.apache.servicecomb.saga.omega.spring.OmegaSpringConfig$$EnhancerBySpringCGLIB$$a2c048e8] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-09-11 19:30:52.437  INFO 38844 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'omegaUniqueIdGenerator' of type [org.apache.servicecomb.saga.omega.context.UniqueIdGenerator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-09-11 19:30:52.442  INFO 38844 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'omegaContext' of type [org.apache.servicecomb.saga.omega.context.OmegaContext] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-09-11 19:30:52.457  INFO 38844 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'compensationContext' of type [org.apache.servicecomb.saga.omega.context.CallbackContext] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-09-11 19:30:52.477  INFO 38844 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'coordinateContext' of type [org.apache.servicecomb.saga.omega.context.CallbackContext] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-09-11 19:30:53.349  INFO 38844 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2018-09-11 19:30:53.378  INFO 38844 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2018-09-11 19:30:53.378  INFO 38844 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.31
2018-09-11 19:30:53.511  INFO 38844 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2018-09-11 19:30:53.512  INFO 38844 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3209 ms
2018-09-11 19:30:54.205  INFO 38844 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2018-09-11 19:30:54.211  INFO 38844 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'metricsFilter' to: [/*]
2018-09-11 19:30:54.212  INFO 38844 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-09-11 19:30:54.212  INFO 38844 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2018-09-11 19:30:54.212  INFO 38844 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2018-09-11 19:30:54.212  INFO 38844 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2018-09-11 19:30:54.212  INFO 38844 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'webRequestLoggingFilter' to: [/*]
2018-09-11 19:30:54.212  INFO 38844 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'applicationContextIdFilter' to: [/*]
2018-09-11 19:30:54.960  WARN 38844 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'coordinateMessageHandler' defined in org.apache.servicecomb.saga.omega.transaction.spring.TransactionAspectConfig: Unsatisfied dependency expressed through method 'coordinateMessageHandler' parameter 3; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.apache.servicecomb.saga.omega.transaction.tcc.ParametersContext' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
2018-09-11 19:30:54.965  INFO 38844 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2018-09-11 19:30:54.972 ERROR 38844 --- [ault-executor-1] a.s.s.o.c.g.GrpcCompensateStreamObserver : Failed to process grpc compensate command.

io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdownNow invoked
	at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420) [grpc-stub-1.14.0.jar:1.14.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.14.0.jar:1.14.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]

2018-09-11 19:30:54.972  INFO 38844 --- [pool-1-thread-1] o.a.s.s.o.c.g.PushBackReconnectRunnable  : Retry connecting to alpha at localhost:8080
2018-09-11 19:30:54.982 ERROR 38844 --- [pool-1-thread-1] o.a.s.s.o.c.g.PushBackReconnectRunnable  : Failed to reconnect to alpha at localhost:8080

io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222) ~[grpc-stub-1.14.0.jar:1.14.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203) ~[grpc-stub-1.14.0.jar:1.14.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132) ~[grpc-stub-1.14.0.jar:1.14.0]
	at org.apache.servicecomb.saga.pack.contract.grpc.TxEventServiceGrpc$TxEventServiceBlockingStub.onDisconnected(TxEventServiceGrpc.java:280) ~[pack-contract-grpc-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.servicecomb.saga.omega.connector.grpc.GrpcClientMessageSender.onDisconnected(GrpcClientMessageSender.java:79) ~[omega-connector-grpc-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.servicecomb.saga.omega.connector.grpc.PushBackReconnectRunnable.run(PushBackReconnectRunnable.java:51) ~[omega-connector-grpc-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.servicecomb.saga.omega.connector.grpc.LoadBalancedClusterMessageSender$2.run(LoadBalancedClusterMessageSender.java:196) [omega-connector-grpc-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_92]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]

2018-09-11 19:30:54.988  INFO 38844 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-09-11 19:30:55.133 ERROR 38844 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 3 of method coordinateMessageHandler in org.apache.servicecomb.saga.omega.transaction.spring.TransactionAspectConfig required a bean of type 'org.apache.servicecomb.saga.omega.transaction.tcc.ParametersContext' that could not be found.

Action:

Consider defining a bean of type 'org.apache.servicecomb.saga.omega.transaction.tcc.ParametersContext' in your configuration.

2018-09-11 19:30:55.138 ERROR 38844 --- [       Thread-2] s.o.c.g.LoadBalancedClusterMessageSender : Failed disconnecting from alpha at localhost:8080

io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222) ~[grpc-stub-1.14.0.jar:1.14.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203) ~[grpc-stub-1.14.0.jar:1.14.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132) ~[grpc-stub-1.14.0.jar:1.14.0]
	at org.apache.servicecomb.saga.pack.contract.grpc.TxEventServiceGrpc$TxEventServiceBlockingStub.onDisconnected(TxEventServiceGrpc.java:280) ~[pack-contract-grpc-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.servicecomb.saga.omega.connector.grpc.GrpcClientMessageSender.onDisconnected(GrpcClientMessageSender.java:79) ~[omega-connector-grpc-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.servicecomb.saga.omega.connector.grpc.LoadBalancedClusterMessageSender.onDisconnected(LoadBalancedClusterMessageSender.java:143) ~[omega-connector-grpc-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.servicecomb.saga.omega.spring.OmegaSpringConfig$1.run(OmegaSpringConfig.java:105) [omega-spring-starter-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]

**Comment by minlywang** [comment]
前段时间还正常

**Comment by WillemJiang** [comment]
Please checkout the latest master branch, the ParameterContext was added recently.

**Comment by minlywang** [comment]
I checked out the lastest master branch yesterday,
Got the same error....

**2018-09-12 11:41:49.289 ERROR 47232 --- [ault-executor-1] a.s.s.o.c.g.GrpcCompensateStreamObserver : Failed to process grpc compensate command.**

io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdownNow invoked
	at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:420) [grpc-stub-1.14.0.jar:1.14.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [grpc-core-1.14.0.jar:1.14.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]

2018-09-12 11:41:49.337  INFO 47232 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-09-12 11:41:49.290  INFO 47232 --- [pool-1-thread-1] o.a.s.s.o.c.g.PushBackReconnectRunnable  : Retry connecting to alpha at localhost:8080
2018-09-12 11:41:49.382 ERROR 47232 --- [pool-1-thread-1] o.a.s.s.o.c.g.PushBackReconnectRunnable  : **Failed to reconnect to alpha at localhost:8080**

io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222) ~[grpc-stub-1.14.0.jar:1.14.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203) ~[grpc-stub-1.14.0.jar:1.14.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132) ~[grpc-stub-1.14.0.jar:1.14.0]
	at org.apache.servicecomb.saga.pack.contract.grpc.TxEventServiceGrpc$TxEventServiceBlockingStub.onDisconnected(TxEventServiceGrpc.java:280) ~[pack-contract-grpc-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.servicecomb.saga.omega.connector.grpc.GrpcClientMessageSender.onDisconnected(GrpcClientMessageSender.java:79) ~[omega-connector-grpc-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.servicecomb.saga.omega.connector.grpc.PushBackReconnectRunnable.run(PushBackReconnectRunnable.java:51) ~[omega-connector-grpc-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.servicecomb.saga.omega.connector.grpc.LoadBalancedClusterMessageSender$2.run(LoadBalancedClusterMessageSender.java:196) [omega-connector-grpc-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_92]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_92]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]

2018-09-12 11:41:49.622 ERROR 47232 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 3 of method coordinateMessageHandler in org.apache.servicecomb.saga.omega.transaction.spring.TransactionAspectConfig required a bean of type 'org.apache.servicecomb.saga.omega.transaction.tcc.ParametersContext' that could not be found.


Action:

Consider defining a bean of type 'org.apache.servicecomb.saga.omega.transaction.tcc.ParametersContext' in your configuration.

2018-09-12 11:41:49.626 ERROR 47232 --- [       Thread-2] s.o.c.g.LoadBalancedClusterMessageSender : **Failed disconnecting from alpha at localhost:8080**

**io.grpc.StatusRuntimeException: UNAVAILABLE: Channel shutdown invoked**
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:222) ~[grpc-stub-1.14.0.jar:1.14.0]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:203) ~[grpc-stub-1.14.0.jar:1.14.0]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:132) ~[grpc-stub-1.14.0.jar:1.14.0]
	at org.apache.servicecomb.saga.pack.contract.grpc.TxEventServiceGrpc$TxEventServiceBlockingStub.onDisconnected(TxEventServiceGrpc.java:280) ~[pack-contract-grpc-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.servicecomb.saga.omega.connector.grpc.GrpcClientMessageSender.onDisconnected(GrpcClientMessageSender.java:79) ~[omega-connector-grpc-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.servicecomb.saga.omega.connector.grpc.LoadBalancedClusterMessageSender.onDisconnected(LoadBalancedClusterMessageSender.java:143) ~[omega-connector-grpc-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at org.apache.servicecomb.saga.omega.spring.OmegaSpringConfig$1.run(OmegaSpringConfig.java:105) [omega-spring-starter-0.3.0-SNAPSHOT.jar:0.3.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]

**Comment by WillemJiang** [comment]
It looks like there are something wrong with the SNAPSHOT deployment.
Can you run the build from root directory?
It forces mvn updated all the artifacts which are built from current code base.

**Comment by minlywang** [comment]
I imported the whole master branch into my eclipse...
It worked...
Thanks
