### ISSUE TITLE
Saga transaction cancel does't work

### ISSUE THREAD

**Issue by minlywang** [apache/incubator-servicecomb-saga#296]
09:20:49.209 [grpc-default-worker-ELG-3-3] INFO  io.grpc.netty.NettyServerTransport.connections - Transport failed

io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: GET / 

	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85) ~[netty-codec-http2-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:314) ~[netty-codec-http2-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251) ~[netty-codec-http2-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450) ~[netty-codec-http2-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[netty-transport-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[netty-transport-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) ~[netty-transport-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) ~[netty-transport-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) ~[netty-transport-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) ~[netty-transport-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[netty-common-4.1.24.Final.jar!/:4.1.24.Final]

	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.24.Final.jar!/:4.1.24.Final]

	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by WillemJiang** [comment]
There is something wrong when Alpha try to call the cancel or confirm method. 
Current Omega doesn't catch the exception and it breaks the callback stream connection, then the cancelTransaction won't be invoked.

[ XNIO-2 task-6] c.i.z.m.web.aop.logging.LoggingAspect : Exception in com.ifelc.z.microservice.service.yiwen.settlement.service.impl.WithdrawServiceImpl.testTransaction() with cause = 'NULL' and exception = 'Error!'

java.lang.RuntimeException: Error!
at com.ifelc.z.microservice.service.yiwen.settlement.service.impl.WithdrawServiceImpl.testTransaction(WithdrawServiceImpl.java:102)
at 

We are planing to fix this kind of corn case next week.

**Comment by minlywang** [comment]
Yes,the client side didn't has a problem.
How to handle server side error "io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: GET /**" ?

**Comment by WillemJiang** [comment]
Hi , 
I guess you just try to access the saga event from the restful API. 
As you may know, Alpha has two ports to provide service, one is for grpc, the other is restful service.
It looks like you just access the grpc service with HTTP GET request.
